### ISSUE TITLE
Not able to obtain all information for quiz objects from MongoDB

### ISSUE THREAD

**Issue by vivjd** [vivjd/Squiz#17]
**Describe the bug**
It appears that the `public List<Quiz> getAllQuizzes()` in the `QuizDataAccessObject` only returns the ObjectID. All other fields returned are null. See the screenshot below to see more details. This is not ideal as we need all attributes for the Quiz entity.

**To Reproduce**
1. Create breakpoint within `public List<Quiz> getAllQuizzes()`
2. Run the debugger and click on the View All Quizzes button.
3. Step over and inspect `resultList`.

**Expected behavior**
All fields are null or 0 for the two sample Quiz objects I've created within the MongoDB quizzes collection.

**Screenshots**
<img width="491" alt="Screen Shot 2023-11-20 at 5 44 32 PM" src="https://github.com/vivjd/Squiz/assets/118199397/2fe8f01a-7e7c-4d55-af6e-f22ff7308dca">

**Additional context**
Due to this bug, the DisplayQuizzes use case does not function properly at the moment. It used to display an error message in the console, but now no error message is displayed when View All Quizzes is clicked, which is probably because the other issues are fixed. I've already checked that all fields have a BSONproperty, so I'm not sure where the error is coming from.

**Comment by mintun-myo-2020** [comment]
which branch is this on?

**Comment by vivjd** [comment]
> which branch is this on?

The DisplayQuizUseCase branch.

**Comment by mintun-myo-2020** [comment]
it works on my end though. the attributes are visible with the toString() method on quiz that i just added

**Comment by mintun-myo-2020** [comment]
also visible on the QuizDataAccessObjectTest.testGetAllQuizzes() test method

**Comment by vivjd** [comment]
This works now, the error seems to be coming from an issue with updating the view instead for DisplayQuiz.
