### ISSUE TITLE
MCQ and Open Ended Question Differentiation

### ISSUE THREAD

**Issue by vivjd** [vivjd/Squiz#19]
Currently working on the AnswerQuestion UseCase. I was wondering how we can differentiate between a MCQ and Open Ended Question (OEQ) that's stored in MongoDB.
- Our current data base structure has that we store each quiz in the database, and the questions are stored with the quizzes. (They are not stored as a separate collection if I understand correctly)
         <img width="649" alt="Screen Shot 2023-11-21 at 12 08 54 AM" src="https://github.com/vivjd/Squiz/assets/118199397/88523e72-079f-410d-9756-c1af8cf706ec">

- When we store the questions, do we store them as an entity, or just extract the relevant fields into the database.
   - i.e. A MCQ will have its question name and answer options stored in the questions array in the quiz, so the entity it is not stored as an entity?
- If that's the case, should we add some sort of attribute to each question that we store to the database, so we can easily access that attribute to determine the question type? Or perhaps, there's some easier way to determine the question type (for instance, based on whether or not if they have an answerOptions field?
- This probably will largely result on how we implement SaveQuiz and how we modify the Question entities if needed.

**Comment by mintun-myo-2020** [comment]
1. Yes the questions are stored with the quizzes, not separated into a different collection
2. Store as entity
3. Maybe we could consider adding a questionType field into the parent class, then set the attribute in the subclasses?

**Comment by vivjd** [comment]
Yes that makes sense, I've added an isMCQ field in the parent class to make it work.
